source 'https://rubygems.org'
gem 'sinatra'

gem 'json'
gem 'dm-postgres-adapter'
gem 'data_mapper'
gem 'mailgun-ruby'
gem 'sinatra-cross_origin', git: 'https://github.com/britg/sinatra-cross_origin.git'
gem 'unicorn'

group :development do
  gem 'dotenv'
end
