version: "2"
services:
  couch:
    image: 3dwardsharp/rebelcricket
    restart: always
    env_file: .env
    expose:
      - 8090
      - 8091
      - 5984
    volumes:
      - /home/core/rebeldata:/opt/couchdb/data
      - /home/core/rebelgfx:/opt/rebelcricket/uploads
  web:
    image: 3dwardsharp/nginx-certbot
    restart: always
    volumes:
      - /home/core/letsencrypt:/etc/letsencrypt
      - ./nginx.template:/etc/nginx/conf.d/nginx.template
    ports:
      - "80:80"
      - "443:443"
    environment:
      - COUCH_SERVER=couch.rebelcricket.com
      - BASE_SERVER=rebelcricket.com
      - ADMIN_SERVER=admin.rebelcricket.com
    command: /bin/bash -c "cron && envsubst '$${COUCH_SERVER},$${BASE_SERVER},$${ADMIN_SERVER}' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  pg:
    restart: always
    env_file: .env
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - /home/core/pgdata:/var/lib/postgresql/data
      - ./init-vendorgoods-db.sh:/docker-entrypoint-initdb.d/init-vendorgoods-db.sh

