web:
  restart: always
  image: hub.sked.site:5000/rebelcricket
  environment:
    - DATABASE_URL=postgres://rebelcricket@pg/rebelcricket
    - MAILGUN_API_KEY=key
    - MAILGUN_DOMAIN=mg.lacuna.club
    - MAIL_GOES_TO=edward@edwardsharp.net
    - SERVE_TEST_INDEX=false
    - VIRTUAL_HOST=http://rebelcricket.lacuna.club
  ports:
    - "80:8080"
  links:
    - pg:pg
  restart: always
  volumes: 
    - /home/core/rebelgfx:/rebelcricket/public/rebelgfx
pg:
  restart: always
  image: postgres:9.6
  volumes:
    - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh